hmsserver4:
    build: .
    # command: gunicorn --debug --log-level debug -b 0.0.0.0:8080 server.gateway:app
    # command: python3 -m server.gateway
    command: ls
    ports:
      - "8080:8080"
    volumes:
        - /home/vagrant/pa2515/server:/server

# redis:
#   image: redis:3.0.2
