hmsserver3:
    build: .
    # command: gunicorn --debug --log-level debug -b 0.0.0.0:8080 server.gateway:app
    command: python3 -m server.gateway
    ports:
      - "8080:8080"
    volumes:
        - .:/server

# redis:
#   image: redis:3.0.2
